Hotel::Hotel.create(name: 'Hilton')
Hotel::Hotel.create(name: '25Hours')
Hotel::Hotel.create(name: 'The Ritz-Carlton')
Hotel::Hotel.create(name: 'Marriott')
Hotel::Hotel.create(name: 'MEININGER')
Hotel::Hotel.create(name: 'Pullman')
Hotel::Hotel.create(name: 'AZIMUT')
Hotel::Hotel.create(name: 'Mövenpick')
Hotel::Hotel.create(name: 'ibis')
Hotel::Hotel.create(name: 'Regent')
